### PR TITLE
(draft) scrape vaccination data

### PR DESCRIPTION
**Pull request by jaimergp**
I saw that https://www.berlin.de/corona/lagebericht/desktop/corona.html now provides vaccination data and tried to write a way to scrape it. I am not too familiar with ruby, but I hope it's a good starting point! Feel free to edit away @knudmoeller!

Thanks!

### CODE REVIEW

**Review by knudmoeller — CHANGES_REQUESTED** [review]
Hi, this is great! I'd like to add the vaccination data to the traffic light file, though, rather than to its own file. It should be added right after the `:indicators`:

```
:indicators => {
    ...
} ,
:vaccination => {
    :total_administered => 
        doc.css("#box-Impfdosen .inner .value").text().gsub(" ","").to_i ,
    :percentage_one_dose => 
        german_to_international_float(doc.css("#box-erstimpfung .inner .value").text().gsub("%","")) ,
    :percentate_two_doses => 
        german_to_international_float(doc.css("#box-zweitimpfung .inner .value").text().gsub("%","")) 
}
```

This would be the only change.

I'm not sure how to best proceed: do you want to resubmit the PR? Alternatively, I could also just do it myself, but then you wouldn't be credited for the contribution. I don't think I can edit your commit without approving it first and then undoing all the unwanted changes.

**Comment by jaimergp** [comment]
You should have write access to my fork! 
image

**Review by knudmoeller — APPROVED** [review]
I've made the changes I mentioned (vaccination data goes into traffic light file, no separate file).

**Comment by knudmoeller** [comment]
Thanks for making me aware of the vaccination data and the PR!

**Comment by jaimergp** [comment]
Yay, thank you!

**Pull request merged**
